# Generated by Django 4.1.3 on 2022-11-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
